name: cdk-blink-payment-processor

# To use the published Docker Hub image without building, run:
#   IMAGE=docker.io/USERNAME/cdk-blink-payment-processor:latest docker compose up -d --no-build

services:
  payment-processor:
    # Build locally or pull from registry by setting IMAGE env var (see note above)
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE:-cdk-blink-payment-processor:local}
    container_name: cdk-blink-payment-processor
    restart: unless-stopped
    environment:
      BLINK_API_URL: ${BLINK_API_URL:-https://api.blink.sv/graphql}
      BLINK_API_KEY: ${BLINK_API_KEY:-changeme}
      BLINK_WALLET_ID: ${BLINK_WALLET_ID:-}
      SERVER_PORT: ${SERVER_PORT:-50051}
      RUST_LOG: ${RUST_LOG:-info}
    ports:
      - "${SERVER_PORT:-50051}:50051"
    # Uncomment to mount a local config file (ensure it isn't committed with secrets)
    # volumes:
    #   - ./config.toml:/app/config.toml:ro
  mintd:
    image: cashubtc/mintd:sha-6496ed6-arm64
    container_name: mint
    ports:
      - "8085:8085"
    environment:
      - CDK_MINTD_URL=https://example.com
      - CDK_MINTD_LN_BACKEND=fakewallet
      - CDK_MINTD_LISTEN_HOST=0.0.0.0
      - CDK_MINTD_LISTEN_PORT=8085
      - CDK_MINTD_MNEMONIC=
      # Database configuration - choose one:
      # Option 1: SQLite (embedded, no additional setup needed)
      - CDK_MINTD_DATABASE=sqlite
      # Option 2: ReDB (embedded, no additional setup needed)
      # - CDK_MINTD_DATABASE=redb
      # Option 3: PostgreSQL (requires postgres service, enable with: docker-compose --profile postgres up)
      # - CDK_MINTD_DATABASE=postgres
      # - CDK_MINTD_DATABASE_URL=postgresql://cdk_user:cdk_password@postgres:5432/cdk_mint
      # Cache configuration
      - CDK_MINTD_CACHE_BACKEND=memory
      # For Redis cache (requires redis service, enable with: docker-compose --profile redis up):
      # - CDK_MINTD_CACHE_REDIS_URL=redis://redis:6379
      # - CDK_MINTD_CACHE_REDIS_KEY_PREFIX=cdk-mintd
      - CDK_MINTD_PROMETHEUS_ENABLED=true
      - CDK_MINTD_PROMETHEUS_ADDRESS=0.0.0.0
      - CDK_MINTD_PROMETHEUS_PORT=9000
    command: [ "cdk-mintd" ]